baseURL = 'https://romanklasen.com/'
languageCode = 'en-us'
title = 'Roman Klasen | Projects'

[hugoVersion]
extended = true

[markup]
# (Optional) To be able to use all Prism plugins, the theme enables unsafe
# rendering by default
# _merge = "deep"
[markup.goldmark]
[markup.goldmark.renderer]
# This setting allows inlining <script> and <style> tags in markdown,
# which is useful and required to use Prism plugins, but may be dangerous
# if the content isn't trustworthy.
unsafe = true

[params]

# dark or light, defaults to light
defaultTheme = "dark"
# gray red green yellow blue purple aqua orange, defaults to blue
themeColor = "green"
# soft medium hard, defaults to medium
themeContrast = "hard"
author = "Roman Klasen"
subtitle = "Particle Physicist"
description = "Particle physicist turned software developer."
email = ""

[params.prism]
languages = ["cpp", "clike", "python"]
plugins = [
    "normalize-whitespace",
    "toolbar",
    "copy-to-clipboard",
    "command-line",
]

# disable katex-html
[params.katex]
enable = false

[build]
# The theme enables writeStats which is required for PurgeCSS
# _merge = "deep"

[outputs]
home = ['html']
section = ['html']
taxonomy = ['html']
term = ['html']

# This hopefully will be simpler in the future.
# See: https://github.com/schnerring/hugo-theme-gruvbox/issues/16
[module]
[[module.imports]]
path = "github.com/schnerring/hugo-theme-gruvbox"

[[module.mounts]]
# required by hugo-mod-json-resume
source = "node_modules/simple-icons/icons"
target = "assets/simple-icons"
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "node_modules/katex"
target = "assets/katex"
[[module.mounts]]
source = "layouts"
target = "layouts"
[[module.mounts]]
source = "static"
target = "static"
[[module.mounts]]
source = "node_modules/prismjs"
target = "assets/prismjs"
[[module.mounts]]
source = "node_modules/prism-themes/themes"
target = "assets/prism-themes"
[[module.mounts]]
source = "node_modules/typeface-fira-code/files"
target = "static/fonts"
[[module.mounts]]
source = "node_modules/typeface-roboto-slab/files"
target = "static/fonts"
[[module.mounts]]
source = "node_modules/@tabler/icons/icons"
target = "assets/tabler-icons"

[params.tagCloud]
enable = false
minFontSizeRem = 0.8
maxFontSizeRem = 2.0

[menu]
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 40

[languages]
[languages.en]
languageName = "English"
weight = 10
[languages.en.params.jsonResume]
present = "present"
